version: "3.9"

services:
  # -------------------------
  # Backend PHP + Nginx
  # -------------------------
  nginx:
    image: nginx:1.29.3-alpine
    container_name: nginx_backend_serv
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/backend/src   # tylko kod źródłowy
    depends_on:
      - php
    networks:
      - backend_network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php_backend_serv
    ports:
      - "${PHP_FPM_PORT}:9000"
    volumes:
      - ./src:/backend/src              # kod źródłowy
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
    networks:
      - backend_network
      - database_network

  # -------------------------
  # MySQL Database
  # -------------------------
  database:
    image: mysql:8.0
    container_name: database_server
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_HOST_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # restart: unless-stopped
    networks:
      - database_network
      - backend_network

  # -------------------------
  # phpMyAdmin
  # -------------------------
  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    # restart: unless-stopped
    depends_on:
      - database
    networks:
      - database_network

  # -------------------------
  # React + Vite Frontend
  # -------------------------
  frontend:
    build: 
      context: .
      dockerfile: ./docker/react/Dockerfile
      target: dev
    container_name: react_frontend_serv
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app:/frontend/app            # tylko kod źródłowy
    depends_on:
      - nginx
    networks:
      - frontend_network
      - backend_network
    command: ["npm", "run", "dev", "--", "--host"]

# -------------------------
# NETWORKS
# -------------------------
networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
  database_network:
    driver: bridge

# -------------------------
# VOLUMES
# -------------------------
volumes:
  mysql_data:
