services:
  database:
    image: mysql:8.0
    container_name: database_serv
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - database-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - database
    networks:
      - database-network

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: laravel_serv
    working_dir: /backend
    # restart: unless-stopped
    volumes:
      - ./src:/backend/app
      - ./bootstrap:/backend/bootstrap
      - ./database:/backend/database
      - ./routes:/backend/routes
      - ./tests:/backend/tests
      - /backend/vendor
    depends_on:
      - database
    networks:
      - database-network
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    # restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:80
    volumes:
      # - ./base:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - backend-network
      - frontend-network

  frontend:
    build:
      context: ./docker/react
    container_name: react_serv
    working_dir: /frontend
    # restart: unless-stopped
    ports:
      - ${FRONTEND_PORT}:5173
    volumes:
      - ./app:/frontend/src
      - ./docker/react/public:/frontend/public
      - ./.env:/frontend/.env
      - /frontend/node_modules
    networks:
      - frontend-network

networks:
  database-network:
    driver: bridge
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
